### ISSUE TITLE
Map filter and number of datasets in collection

### ISSUE THREAD

**Issue by lhmarsden** [metno/metsis-drupal#44]
I have observed this issue on both SIOS and the NBS staging area, so I believe it is probably an issue on all configurations.

When one does a map filter, the number that states the number of datasets in a collection does not change. So if the map filter includes only 4 out of the 10 datasets in the collection, the button would continue to state that there are 10 datasets. 

This could be misleading. It should say either 4 or perhaps 4 out of 10.

**Comment by steingod** [comment]
There is an issue with the search interface in general for the time being. Not sure if it is a consequence of some upgrades, but think @magnarem  is checking these issues.

**Comment by magnarem** [comment]
@lhmarsden . I have now fixed this issue and updated [nbs-staging.met.no](url) and [metsis-staging.met.no](url) for testing this.

The question is what we do with the child button if no children are found within a collection when using the map filter.
Now the child button will be gone if there are no children within the collection matching the map filter. but the parent might still show if the full_text string or date in the search matches, it is not that easy to remove parents from the main search when counting the children..but it might be possible. 

I do not know what is the best solution. maybe @steingod have some comments.

I see three possible solutions.

1. just show the parent, since the parent matched the search, but no children within this collection matched, so the "Child"-button will not be displayed.
2. Display the child-button with all possible children. (Then it really does not take the filtering into account)
3. Try to remove that parent from the main search, so the record does not show. (this can be a bit difficult to solve, but should be possible.)

**Comment by lhmarsden** [comment]
That's great, Magnar.

So you have done a search, that returned 10 out of 100 of the children for a collection. Then you do a map search and 0 out of the 100 are left.

In my opinion the parent should no longer be visible. I think it is most logical that the map search should work in the same was as any of filter option.

If you refined your search using a different filter option (e.g. date) and it returned 0 children, the parent wouldn't be displayed right? If so, the map search should work in the same way - sorry for advocating for the most difficult option to implement!

________________________________

**Comment by magnarem** [comment]
I consider this closed now. The logic is implemented, and there is a configuration to turn on and of hiding of parents, if children are 0. If this configuration is not enabled. All children will be shown.

**Comment by magnarem** [comment]
Closing this
